// Package daemon provides gRPC service types for the A2 Local Daemon adapter.
// These types define the gRPC service contract without requiring protobuf
// code generation. In production, these would be generated from a .proto file.
package daemon

import (
	"context"

	"google.golang.org/grpc"
)

// GovernRequest is an incoming governance check from an agent process.
type GovernRequest struct {
	CallId          string `json:"call_id"`
	AgentId         string `json:"agent_id"`
	SessionId       string `json:"session_id"`
	ToolId          string `json:"tool_id"`
	ArgsJson        string `json:"args_json"` // JSON-encoded args
	WaitForApproval bool   `json:"wait_for_approval"`
}

// GovernResponse is the governance decision returned to the agent.
type GovernResponse struct {
	Effect        string `json:"effect"`
	RuleId        string `json:"rule_id"`
	ReasonCode    string `json:"reason_code"`
	Reason        string `json:"reason"`
	DeferToken    string `json:"defer_token,omitempty"`
	PolicyVersion string `json:"policy_version"`
	LatencyMs     int64  `json:"latency_ms"`
}

// KillRequest triggers the kill switch for an agent.
type KillRequest struct {
	AgentId string `json:"agent_id"`
}

// KillResponse acknowledges the kill switch activation.
type KillResponse struct {
	Success bool `json:"success"`
}

// FarameshDaemonServer is the interface for the gRPC daemon service.
type FarameshDaemonServer interface {
	Govern(context.Context, *GovernRequest) (*GovernResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
}

// UnimplementedFarameshDaemonServer implements FarameshDaemonServer with
// unimplemented methods for forward compatibility.
type UnimplementedFarameshDaemonServer struct{}

func (UnimplementedFarameshDaemonServer) Govern(context.Context, *GovernRequest) (*GovernResponse, error) {
	return nil, grpc.Errorf(12, "method Govern not implemented") //nolint:staticcheck
}

func (UnimplementedFarameshDaemonServer) Kill(context.Context, *KillRequest) (*KillResponse, error) {
	return nil, grpc.Errorf(12, "method Kill not implemented") //nolint:staticcheck
}

// RegisterFarameshDaemonServer registers a FarameshDaemonServer with a gRPC server.
// In production this would be generated by protoc-gen-go-grpc.
func RegisterFarameshDaemonServer(_ *grpc.Server, _ FarameshDaemonServer) {
	// Registration placeholder — production uses protobuf service descriptors.
	// The actual server handles requests through the gRPC service handler pattern.
}
